### PR TITLE
fix task name conflict

### PR DESCRIPTION
**Pull request by Bloodyhacker**

### CODE REVIEW

**Review by makosblade — APPROVED** [review]
LGTM. Let's wait another 15 minutes to merge, I'm waiting for some builds to finish.

**Comment by geekbeast** [comment]
This is fine, but may cause issues for projects that do not have shadow jar builds. You should hide it behind a flag that is set, before script is loaded.

**Comment by geekbeast** [comment]
Otherwise, LGTM

**Comment by geekbeast** [comment]
Another way might be to check whether the shadowJar task exists.

**Comment by makosblade** [comment]
Might even want to just put the maven publishing stuff for shadow jars into the parasol projects build.gradle since it's the only one with shadow stuff

**Comment by Bloodyhacker** [comment]
Right, we can just put the maven publishing stuff for shadow jars into parasol and kindling projects.
I think kindling also needs to have shadowJar because it will be submitted to databricks' spark cluster as a Job

**Comment by Bloodyhacker** [comment]
So, I will decline this PR and make PR in parasol and kindling instead

**Pull request closed without merging**
